### ISSUE TITLE
Trouble Loading Models in Different Python Environments

### ISSUE THREAD

**Issue by avzero07** [interseismic/generalized-phase-detection#3]
While attempting to check `gpd_predict.py` I ran into some trouble when loading the model JSON.

```
(torch-tensorflow) PS C:\Users\aksha\Desktop\generalized-phase-detection> python gpd_predict.py -V -I anza2016.in -O anza2016.out
Traceback (most recent call last):
  File "gpd_predict.py", line 164, in <module>
    model = model_from_json(loaded_model_json, custom_objects={'tf':tf})
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\saving\model_config.py", line 122, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 171, in deserialize
    return generic_utils.deserialize_keras_object(
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 354, in deserialize_keras_object
    return cls.from_config(
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2238, in from_config
    return functional.Functional.from_config(
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 616, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 1204, in reconstruct_from_config
    process_layer(layer_data)
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 1186, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 171, in deserialize
    return generic_utils.deserialize_keras_object(
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 354, in deserialize_keras_object
    return cls.from_config(
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1005, in from_config
    function = cls._parse_function_from_config(
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1057, in _parse_function_from_config
    function = generic_utils.func_load(
  File "D:\Development\Anaconda\envs\torch-tensorflow\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 457, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)
```

A little bit of digging helped me narrow down the issue and it appears to be related to the Lambda layers in the model.

![image](https://user-images.githubusercontent.com/27913879/124986047-0725e080-dff0-11eb-940b-afb5c4014ecf.png)

I'm not sure if the use of serialized bytecode in your JSON is for obscuring the details. If not, do you mind sharing the python code for constructing your model?

Alternatively, could you specify the exact environment that was used to save your model JSON? It would be nice to include the environment info in the README.

**Comment by jamm1985** [comment]
Hi! @avzero07 

I just created pull request

https://github.com/interseismic/generalized-phase-detection/pull/4

Please try this.

**Comment by avzero07** [comment]
Hey @jamm1985 thanks for responding. Your dependency list is extensive. I did some experimenting and found out that just meeting the following requirements helps get things running.

I set up a new virtual environment with python 3.6 and then installed the following (their respective dependencies were automatically installed).

```
keras==2.2.2
obspy==1.2.2
h5py==2.10.0
```

It helps to install in this order to force the install of h5py 2.10.0. Otherwise, the keras installation will install a higher version of h5py which will cause issues when loading the model weights.

**Comment by avzero07** [comment]
While my immediate issue has been solved, the original one still stands. It appears that the bytecode for the lambda layers in the trained model shipped by the authors can only be loaded in python 3.6.

1. It would help if the authors share their class for the gpd model or the portion of code (in case it was created as a sequential model).
 
2. Alternatively, if the model is constructed exactly per the specification in their paper then it might be possible to create it and then attempt to plug in the provided weights. This will involve some amount of trial and error for sure. I may try this out at some point if I can find the time. If I do and the effort is successful I will report back here.

**Comment by jamm1985** [comment]
In https://github.com/jamm1985/seismo-performer we redeployed original GPD model to tf 2.5.0. So it works by several lines of code.

/cc @avzero07
